env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 80
    lines: 24

  padding:
    x: 2
    y: 2

draw_bold_text_with_bright_colors: true

font:
  size: 10

# Color schemes
schemes:
  breeze: &breeze
      primary:
        background: '0x232627'
        foreground: '0xfcfcfc'

        dim_foreground: '0xeff0f1'
        bright_foreground: '0xffffff'
        dim_background: '0x31363b'
        bright_background: '0x000000'

      # Normal colors
      normal:
        black: '0x232627'
        red: '0xed1515'
        green: '0x11d116'
        yellow: '0xf67400'
        blue: '0x1d99f3'
        magenta: '0x9b59b6'
        cyan: '0x1abc9c'
        white: '0xfcfcfc'

      # Bright colors
      bright:
        black: '0x7f8c8d'
        red: '0xc0392b'
        green: '0x1cdc9a'
        yellow: '0xfdbc4b'
        blue: '0x3daee9'
        magenta: '0x8e44ad'
        cyan: '0x16a085'
        white: '0xffffff'

      # Dim colors
      dim:
        black: '0x31363b'
        red: '0x783228'
        green: '0x17a262'
        yellow: '0xb65619'
        blue: '0x1b668f'
        magenta: '0x614a73'
        cyan: '0x186c60'
        white: '0x63686d'

colors: *breeze

# Basically default key bindings
key_bindings:
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: Insert,    mods: Shift,         action: PasteSelection              }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Equals,    mods: Control,       action: IncreaseFontSize            }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: F11,       mods: None,          action: ToggleFullscreen            }
  - { key: Paste,     mods: None,          action: Paste                       }
  - { key: Copy,      mods: None,          action: Copy                        }
  - { key: L,         mods: Control,       action: ClearLogNotice              }
  - { key: L,         mods: Control,       chars: "\x0c"                       }
  - { key: PageUp,    mods: None,          action: ScrollPageUp,   mode: ~Alt  }
  - { key: PageDown,  mods: None,          action: ScrollPageDown, mode: ~Alt  }
  - { key: Home,      mods: Shift,         action: ScrollToTop,    mode: ~Alt  }
  - { key: End,       mods: Shift,         action: ScrollToBottom, mode: ~Alt  }

